### ISSUE TITLE
Patio light not on

### ISSUE THREAD

**Issue by frederickcwong** [frederickcwong/jarvis#13]
Oct 1 at sunset

**Comment by frederickcwong** [comment]
Update the automation yaml code directly. I suspect the sun.sun state has not yet changed when the "sun rise" and "sun set" are triggered.

Using this as trigger
```yaml
  - platform: state
    entity_id: sun.sun
``` 

```yaml
  - platform: sun
    event: sunrise
    offset: 0
  - platform: sun
    event: sunset
    offset: 0
```

Let's see if that works tomorrow
